# Generated by Django 4.1 on 2022-08-18 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн/Оффлайн')),
                ('it_stack', models.CharField(max_length=150, verbose_name='Направление в IT')),
                ('work_exp', models.PositiveSmallIntegerField(verbose_name='Стаж работы')),
                ('location', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
